name: aviary
description: A command line application for managing Dart and Flutter repos.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  github: ^9.24.0
  http: ^1.2.2
  path: ^1.9.1
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
