issues:
  - title: "Write the spec"
    assignees: []
    body: ""
  - title: "Language tests"
    assignees: []
    body: ""
  - title: "Co19 tests - add tests"
    assignees: []
    body: ""
  - title: "Implement feature in the CFE"
    assignees: []
    body: ""
  - title: "Analyzer implementation"
    assignees: []
    body: ""
  - title: "Tests validating as passing (Tracking via Google Sheet)"
    assignees: []
    body: ""
  - title: "Syntax highlighters implementation"
    assignees: []
    body: ""
  - title: "DDC implementation"
    assignees: []
    body: ""
  - title: "Dart2js implementation"
    assignees: []
    body: ""
  - title: "VM implementation"
    assignees: []
    body: ""
  - title: "Build system support"
    assignees: []
    body: ""
  - title: "Web debugging support"
    assignees: []
    body: ""
  - title: "Core library updates"
    assignees: []
    body: ""
  - title: "Analysis server / IDE"
    assignees: []
    body: ""
  - title: "dart_style support"
    assignees: []
    body: ""
  - title: "dartdoc implementation"
    assignees: []
    body: ""
  - title: "Cider support"
    assignees: []
    body: ""
  - title: "Kythe implementation"
    assignees: []
    body: ""
  - title: "Angular compiler implementation"
    assignees: []
    body: ""
  - title: "Intellij implementation"
    assignees: []
    body: ""
  - title: "Language feature docs"
    assignees: []
    body: ""
  - title: "VM service protocol support"
    assignees: []
    body: ""
  - title: "VM debugging support"
    assignees: []
    body: ""
  - title: "linter support"
    assignees: []
    body: ""
