issues:
  - title: "Feature Spec"
    assignees: []
    body: ""
  - title: "Language Tests"
    assignees: []
    body: ""
  - title: "co19 Tests"
    assignees: []
    body: ""
  - title: "Language and co19 Tests Passing"
    assignees: []
    body: ""
  - title: "CFE Implementation"
    assignees: []
    body: ""
  - title: "Analyzer Implementation"
    assignees: []
    body: ""
  - title: "Analysis Server Implementation"
    assignees: []
    body: ""
  - title: "Dartdoc Implementation"
    assignees: []
    body: ""
  - title: "DDC Implementation"
    assignees: []
    body: ""
  - title: "Dart2js Implementation"
    assignees: []
    body: ""
  - title: "Web Debugging Support"
    assignees: []
    body: ""
  - title: "VM Implementation"
    assignees: []
    body: ""
  - title: "VM Service Protocol Support"
    assignees: []
    body: ""
  - title: "VM Debugging Support"
    assignees: []
    body: ""
  - title: "Build System Support"
    assignees: []
    body: ""
  - title: "Core Library Updates"
    assignees: []
    body: ""
  - title: "dart_style Formatting Support"
    assignees: []
    body: ""
  - title: "Intellij Support"
    assignees: []
    body: ""
  - title: "VSCode Support"
    assignees: []
    body: ""
  - title: "Cider Support"
    assignees: []
    body: ""
  - title: "Kythe Implementation"
    assignees: []
    body: ""
  - title: "Angular Compiler Implementation"
    assignees: []
    body: ""
  - title: "Language Feature Documentation"
    assignees: []
    body: ""
